server:
  port: 10900  #程序启动后的端口，也就是Tomcat的端口，我们也可以自己定义
spring:
  application:
    name: apigetway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true   # 显示ip
