server:
  port: 9100  #程序启动后的端口，也就是Tomcat的端口，我们也可以自己定义
spring:
  application:
    name: consumer-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
turbine:
  aggregator:
    cluster-config: CONSUMER-ORDER-HYSTRIX
  app-config: consumer-order-hystrix

