server:
  port: 8900  #程序启动后的端口，也就是Tomcat的端口，我们也可以自己定义
spring:
  application:
    name: consumer-order-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
logging:
      level:
        com.mysqlSpringCould.feign.FeignClient2: debug #给指定的feign 指定输出的日志级别，只有在debug的情况下才会打印数据